#!/usr/bin/env python3
"""Pack assets/*.bin into include/logo.h as XBM bitmaps for u8g2.drawXBM().

Source assets are one eye each: 64 wide x 128 tall, row-major, MSB-first.
The panel is 128x64 landscape, so each frame is rotated 90 degrees clockwise
and repacked as XBM (row-major, LSB-first).
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT = ROOT / "logo.h"

SRC_W, SRC_H = 64, 128
DST_W, DST_H = SRC_H, SRC_W
EXPECTED_BYTES = SRC_W * SRC_H // 8


def to_ident(stem: str) -> str:
    return re.sub(r"\W", "_", stem) + "_bits"


def rotate_cw_to_xbm(data: bytes) -> bytes:
    def src_pixel(x, y):
        n = y * SRC_W + x
        return data[n >> 3] >> (7 - (n & 7)) & 1

    out = bytearray(DST_W * DST_H // 8)
    for dy in range(DST_H):
        for dx in range(DST_W):
            if src_pixel(dy, SRC_H - 1 - dx):
                n = dy * DST_W + dx
                out[n >> 3] |= 1 << (n & 7)   # XBM: LSB is leftmost pixel
    return bytes(out)


def main():
    bin_files = sorted(ASSETS.glob("*.bin"))
    if not bin_files:
        raise SystemExit(f"no .bin files found in {ASSETS}")

    idents = []
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by scripts/gen_logo_header.py - do not edit by hand.",
        f"// Each frame is one eye, rotated to {DST_W}x{DST_H} XBM.",
        "",
    ]

    for path in bin_files:
        data = path.read_bytes()
        if len(data) != EXPECTED_BYTES:
            raise SystemExit(
                f"{path.name}: expected {EXPECTED_BYTES} bytes for "
                f"{SRC_W}x{SRC_H}, got {len(data)}"
            )

        ident = to_ident(path.stem)
        idents.append((path.stem, ident))
        hex_bytes = ", ".join(f"0x{b:02x}" for b in rotate_cw_to_xbm(data))

        lines.append(f"static const unsigned char {ident}[] U8X8_PROGMEM = {{")
        lines.append(f"  {hex_bytes}")
        lines.append("};")
        lines.append("")

    by_stem = dict(idents)
    pairs = []
    for stem, ident in idents:
        if not stem.endswith("-left"):
            continue
        expression = stem[: -len("-left")]
        right = by_stem.get(f"{expression}-right")
        if right is None:
            raise SystemExit(f"{stem}.bin has no matching {expression}-right.bin")
        pairs.append((expression, ident, right))

    lines.append("struct EyePair {")
    lines.append("  const char *name;")
    lines.append("  const unsigned char *left;")
    lines.append("  const unsigned char *right;")
    lines.append("};")
    lines.append("")
    lines.append("static const EyePair eye_pairs[] = {")
    for expression, left, right in pairs:
        lines.append(f'  {{ "{expression}", {left}, {right} }},')
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t EYE_PAIR_COUNT = {len(pairs)};")
    lines.append(f"#define EYE_WIDTH {DST_W}")
    lines.append(f"#define EYE_HEIGHT {DST_H}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {len(bin_files)} bitmaps ({DST_W}x{DST_H}) to {OUT}")


if __name__ == "__main__":
    main()
